- name: Pull docker image of Calculator
  hosts: ubuntu22
  tasks:
    - name: Start docker service
      service:
        name: docker
        state: started

    - name: pull docker image
      shell: docker pull guninjain/my-calc-app:{{build_num}}

    - name: running container
      shell: docker run -it -d guninjain/my-calc-app:{{build_num}}

